name: Deploy to Google Cloud Container

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud credentials
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: YOUR_PROJECT_ID  # Replace with your Google Cloud project ID
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}  # Add your service account key to GitHub Secrets

    - name: Configure Docker to use Google Cloud Container Registry
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME:latest .
      
    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME:latest
      
    - name: Deploy to Google Cloud (Google Kubernetes Engine / Cloud Run)
      run: |
        gcloud run deploy YOUR_SERVICE_NAME \
          --image gcr.io/YOUR_PROJECT_ID/YOUR_I
